name: PDF Downloader & Merger

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 7 * *'  # jeden 7. des Monats um 03:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install dependencies (wkhtmltopdf, Ghostscript, Python packages)
      run: |
        sudo apt-get update
        sudo apt-get install -y wkhtmltopdf ghostscript
        pip install -r requirements.txt

    - name: Set current date and filename
      id: set_date
      run: |
        echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

    - name: Run PDF Script
      run: python pdf_downloader.py

    - name: Collect PDF Parts
      run: |
        mkdir out
        mv rechtsvorschriften_*_part*.pdf out/

    - name: Create GitHub Release and Upload all PDF parts
      uses: softprops/action-gh-release@v1
      with:
        tag_name: pdf-${{ steps.set_date.outputs.date }}
        name: "Rechtsvorschriften PDF ${{ steps.set_date.outputs.date }}"
        body: "Automatisch generierte Teil-PDFs vom ${{ steps.set_date.outputs.date }} mit max. 512 MB pro Datei."
        files: out/*.pdf
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
