name: PDF Downloader & Merger

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 7 * *'  # jeden 7. des Monats um 03:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DATE: ${{ steps.set_date.outputs.date }}
      PDF_NAME: ${{ steps.set_date.outputs.pdf }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wkhtmltopdf
        pip install -r requirements.txt

    - name: Set current date
      id: set_date
      run: |
        echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
        echo "pdf=rechtsvorschriften_$(date +'%Y-%m-%d').pdf" >> $GITHUB_OUTPUT

    - name: Run PDF Script
      run: python pdf_downloader.py

    - name: Create GitHub Release and Upload PDF
      uses: softprops/action-gh-release@v1
      with:
        tag_name: pdf-${{ env.DATE }}
        name: "Rechtsvorschriften PDF ${{ env.DATE }}"
        body: "Automatisch generiertes PDF vom ${{ env.DATE }} mit aktuellen Rechtsvorschriften."
        files: ${{ env.PDF_NAME }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
